# Backend Dockerfile
FROM node:20-alpine

WORKDIR /app

COPY server/package*.json ./

RUN npm install

COPY server/src ./src
COPY server/tsconfig.json ./

RUN npm run build

EXPOSE 4000

CMD ["npm", "start"]
